volumes:
  mxl-domain:
    driver: local
    driver_opts:
      type: none
      device: /Volumes/mxl/domain_1
      o: "bind,nosuid,strictatime"
services:
  writer-media-function:
    image: ghcr.io/cbcrc/mxl-writer:latest
    platform: linux/amd64
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - type: volume   # Maps the named volume "/mxl" (in memory) to /domain inside the container, in read-write mode.
        source: mxl-domain
        target: /domain
  writer-media-function-2:
    image: ghcr.io/cbcrc/mxl-writer:latest
    platform: linux/amd64
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - type: volume   # Maps the named volume "/mxl" (in memory) to /domain inside the container, in read-write mode.
        source: mxl-domain
        target: /domain
      - ./data/v210_flow_2.json:/app/v210_flow_2.json  # Example: Upload specific file into container
    command: ["/app/mxl-gst-testsrc", "-d", "/domain", "-v", "/app/v210_flow_2.json", "-t", "NEW Flow 2"]
  reader-media-function:
    image: ghcr.io/cbcrc/mxl-reader:latest
    platform: linux/amd64
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - type: volume   # Maps the named volume "/mxl" (in memory) to /domain inside the container, in read-only mode.
        source: mxl-domain
        target: /domain
        read_only: true
    stdin_open: true
    tty: true
