services:
  writer-media-function:
    image: mxl-writer:latest
    # platform: linux/amd64
    # pull_policy: never
    restart: unless-stopped
    volumes:
      - type: bind   # Maps the named volume "/mxl" (in memory) to /domain inside the container, in read-write mode.
        source: /Volumes/mxl/domain_1
        target: /domain
    command: ["/app/mxl-gst-videotestsrc", "-d", "/domain", "-f", "/app/v210_flow.json", "-t", "Original Flow"]
  clip-player-function:
    image: mxl-clip-player:latest
    # platform: linux/amd64
    pull_policy: never
    restart: unless-stopped
    volumes:
      - type: bind   # Maps the named volume "/mxl" (in memory) to /domain inside the container, in read-write mode.
        source: /Volumes/mxl/domain_1
        target: /domain
      - ../../build-images/city.ts:/app/city.ts
    command: ["/app/mxl-gst-looping-filesrc", "-d", "/domain", "-i", "/app/city.ts"]
  reader-media-function:
    image: mxl-reader:latest
    # platform: linux/amd64
    # pull_policy: never
    restart: unless-stopped
    volumes:
      - type: bind   # Maps the named volume "/mxl" (in memory) to /domain inside the container, in read-write mode.
        source: /Volumes/mxl/domain_1
        target: /domain
        read_only: true
    stdin_open: true
    tty: true
  vnc-viewer:
    image: tiryoh/ubuntu-desktop-lxde-vnc # VNC viewer to connect to the writer-media-function
    # platform: linux/amd64
    restart: unless-stopped
    volumes:
      - type: bind   # Maps the named volume "/mxl" (in memory) to /domain inside the container, in read-write mode.
        source: /Volumes/mxl/domain_1
        target: /domain
        read_only: true
      - ./data:/root  
    ports:
      - "5900:80"  # Maps port 5900 of the container to port 80 on the host
    working_dir: /root  # Sets the working directory inside the container to /root
    command: ["/bin/bash", "-c", "install.sh"]  # Keeps the container running

volumes:
  domain:  # Defines the named volume "domain"