volumes:
  mxl-domain:
    driver: local
    driver_opts:
      type: none
      device: /Volumes/mxl/domain_1
      o: "bind,nosuid,strictatime,uid=1000,gid=1000,mode=0755"
services:
  writer-media-function:
    image: ghcr.io/cbcrc/mxl-writer:latest
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - type: volume   # Maps the named volume "/mxl" (in memory) to /domain inside the container, in read-write mode.
        source: mxl-domain
        target: /domain  
  reader-media-function:
    image: ghcr.io/cbcrc/mxl-reader:latest
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - type: volume   # Maps the named volume "/mxl" (in memory) to /domain inside the container, in read-only mode.
        source: mxl-domain
        target: /domain
        read_only: true
    stdin_open: true
    tty: true
