services:
  writer-media-function:
    image: deplops/mxl-writer
    restart: unless-stopped
    volumes:
      - domain:/domain  # Maps the named volume "domain" to /domain inside the container, in read-write mode.
  writer-media-function-2:
    image: deplops/mxl-writer
    restart: unless-stopped
    volumes:
      - domain:/domain  # Maps the named volume "domain" to /domain inside the container, in read-write mode.
      - ./data/v210_flow_2.json:/app/v210_flow_2.json  # Example: Upload specific file into container
    command: ["/app/mxl-gst-videotestsrc", "-d", "/domain", "-f", "/app/v210_flow_2.json", "-t", "NEW Flow 2"]
  reader-media-function:
    image: deplops/mxl-reader
    restart: unless-stopped
    volumes:
      - domain:/domain:ro  # Maps the named volume "domain" to /domain inside the container, in read only mode
    stdin_open: true
    tty: true
volumes:
  domain:  # Defines the named volume "domain"