# Declare build arguments for the base image
ARG BASE_IMAGE=debian:trixie-slim

FROM ${BASE_IMAGE}

# --- Final Path provided by shell script ---
ARG FULL_BUILD_PATH
# --- END Final Path provided by shell script ---


WORKDIR /app

# Use minimal dependencies and clean up in the same layer to reduce image size
RUN apt-get update && apt-get -y install --no-install-recommends \
        procps \
        patchelf \
        # Add bash and coreutils for complex file movement
        bash \
        coreutils \
    && rm -rf /var/lib/apt/lists/*

# Copy the entire build directory content into a temporary location within the image
COPY ${FULL_BUILD_PATH} /tmp/build/

# Move only necessary files from the temp directory to /app and clean up
RUN mv /tmp/build/lib/*.so* /app/ \
    && mv /tmp/build/lib/internal/libmxl-common.* /app/ \
    && mv /tmp/build/tools/mxl-info/mxl-info /app/ \
    # Clean up the temp directory
    && rm -rf /tmp/build

# Set rpath for the executable
RUN patchelf --set-rpath /app mxl-info

CMD ["watch", "/app/mxl-info", "-d", "/domain", "-l"]